Added UnigueList
SpiNNakerManchester/SpiNNUtils pull request #119
Opened 2020-07-30 06:46 UTC by Christian-B

This is a simple override of list that (I hope) intercepts any of the methods that could add elements to the list and silently removes any duplicates.

Differences to OrderedSet are.
1. Has the list interface including indexing
2. May well be slower on any method which changes it or check membership.
3. Probably smaller memory size

2020-07-30 07:05 UTC, Christian-B commented
Much slower expesially on bigger lists!
UnigueList took 7.763265371322632 compared to OrderedSet of  0.024962663650512695

import random
import time
from spinn_utilities.unigue_list import UnigueList
from spinn_utilities.ordered_set import OrderedSet

data = [random.randint(1, 10000) for i in range(100000)]

start = time.time()
ul = UnigueList()
for foo in data:
    ul.append(foo)
print(len(ul))
print (time.time()-start)
start = time.time()
os = OrderedSet()
for foo in data:
    os.add(foo)
print(len(ul))
print (time.time()-start)

2020-12-01 17:48 UTC, dkfellows requested changes
Needs a bit of work.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/unigue_list.py
> +class UnigueList(list):
Please change the name to `UniqueList`.
Filename must also change to `unique_list.py`.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/unigue_list.py
> +        :return: a new list
You _need_ a blank line before this line.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/unigue_list.py
> +        note:  If the object was already in the list it is removed and then
Better to write as:
```
        .. note::
            If the object was already in the list it is removed and then
```
as that renders differently.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/unigue_list.py
> +        :return: a new list with a single copy in of all items in the first
Blank line needed before this line

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/unigue_list.py
> +        :rtype: UnigueList
Blank line needed before this line

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/unigue_list.py
> +        note:  If the object was already in the list it is removed and then
See previous comment about `.. note::`

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/set_list.py
> +        Creates a list like object and fills in the intial values igornoring
Don't normally need a descriptive paragraph on an `__init__` method.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/set_list.py
> +        :return: a new list
Blank line needed before this line.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/set_list.py
> +        note:  If the object was already in the list it is removed and then
See other comment about `.. note::`

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/set_list.py
> +        :return: a new list with a single copy in of all items in the first
Blank line needed before this line.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/set_list.py
> +        :rtype: UnigueList
Blank line needed before this line.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/set_list.py
> +        Raises KeyError if the set is empty.
Should be:
```
    :raises KeyError: if the set is empty.
```
and should have a blank line before it.

2020-12-01 17:48 UTC, dkfellows commented on spinn_utilities/set_list.py
> +        If the element is not a member, raise a KeyError.
Should be:
```
    :raises KeyError: If the element is not a member.
```

2020-12-02 07:54 UTC, Christian-B commented
While I agree with all of @dkfellows comments I will not fix as this implementations shows it is significantly slower than OrderedSet and also much slower than our SetList.
The larger the resulting set will get the worse the difference.

See test.py.

My suggestion is to close this PR.

2022-08-16 09:44 UTC, Christian-B commented
too slow and not needed.

2022-08-16 09:44 UTC, closed without merging