treat an empty list as a singleton
SpiNNakerManchester/SpiNNUtils pull request #133
Opened 2021-01-25 11:16 UTC by Christian-B

An alternative to https://github.com/SpiNNakerManchester/SpiNNUtils/pull/131

2021-01-25 11:19 UTC, rowleya approved these changes
Looks fine - might be useful to have a test for the odd case this is covering

2021-01-25 11:53 UTC, alan-stokes requested changes

2021-01-25 11:53 UTC, alan-stokes commented on unittests/ranged/test_list.py
> +    rl.set_value_by_ids(ids=[1], value=[[2]])
this is not what the test script is doing. the test script is 
rl.set_value_by_ids(ids=[1], value=[2])

2021-01-26 07:38 UTC, Christian-B commented
Wrong fix

2021-01-26 07:38 UTC, closed without merging